#!/bin/bash

for(( i=16; i<21; ++i ))
do 
mkdir "cascades/cascade_$i"
opencv_traincascade -data "cascades/cascade_$i" -vec "good_file/sampleses/samples_$i.vec" -bg "bad_file/bad_$i.dat" -numStages 16 -minhitrate 0.999 -maxFalseAlarmRate 0.4 -numPos 500 -numNeg 1000 -w 10 -h 15 -mode ALL -precalcValBufSize 2048 -precalcIdxBufSize 2048
done